version: '3.4'

services:
  db:
    image: postgres:16  # <--- SỬA CHỖ NÀY (Đổi từ latest sang 16)
    container_name: my_portfolio_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: PortfolioDb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: